### PR TITLE
Default db location to `~/.hyperirc.db`

### PR DESCRIPTION
**Pull request by rahatarmanahmed**
Regarding https://github.com/mafintosh/hyperirc/issues/3#issuecomment-225338194

Maybe deprecate older versions or something with a message telling them to move their db to the new location?

### CODE REVIEW

**Comment by mafintosh** [comment]
Interesting idea. Lets try it! Could you add this to README as well?

**Comment by rahatarmanahmed** [comment]
Done!

**Comment by mafintosh** [comment]
I'll just major bump this

**Comment by mafintosh** [comment]
Out in 2.0.0. Thanks.

**Comment by mafintosh** [comment]
Btw, we should make multiple channel arguments work so we could tail multiple channels in one process _wink wink_

**Pull request merged**
